# Generated by Django 5.2.3 on 2025-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_produto', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
